//
//  HomeViewController.swift
//  GitHub
//
//  Created by Andre Firmo on 16/02/21.
//  Copyright (c) 2021 Andre Jardim Firmo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic: class{
  
}

class HomeViewController: UIViewController {
    @IBOutlet weak var userSeach: UITextField!

    override func viewDidLoad()
    {
    super.viewDidLoad()
   
    }
  
    @IBAction func seachUser(_ sender: Any) {
    }
}
